### PR TITLE
`build/pkgs/python3` 3.13.0rc1, require Python >= 3.10, `numpy` 2.1.1, `scipy` 1.14.1, `pillow` 10.4.0, `cffi` 1.17.0, `networkx` 3.3, `sphinx` 8, `ipython` 8.26

### PR DESCRIPTION
**Pull request by mkoeppe**
- https://www.python.org/downloads/release/python-3130rc1/
- #29756

The package upgrades done here require dropping support for Python 3.9.
- https://github.com/numpy/numpy/releases/tag/v2.1.0rc1

Per https://repology.org/project/python/versions, Python 3.9 is the newest supported Python version on:
- `debian-bullseye` (end of standard support 2024-08; EOL LTS 2026-08)
- `opensuse-15.3` (past EOL)
- `slackware-15.0`
- `ubuntu-focal` (end of standard support 2025-04; EOL 2032-04)
- see also #32074

### :memo: Checklist

- [x] The title is concise, informative, and self-explanatory.
- [ ] The description explains in detail what this PR is about.
- [ ] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation accordingly.

### :hourglass: Dependencies

- Depends on #36957 (removes `_crypt`)
- Depends on cffi 1.16.0 + https://github.com/python-cffi/cffi/pull/24
- Depends on #37834 
- Depends on #38101 
- Depends on #38226
- Depends on #38227
- ~~Depends on Python 3.13 support in SciPy 1.13.x~~ (SciPy 1.14.0 drops Python 3.9)
- Depends on #38521 (merged)
- Depends on #38549 (merged `-Xours`)
- Depends on reverting #38619

### CODE REVIEW

**Comment by mkoeppe** [comment]
Except for cffi, builds OK, but starting up Sage gives:
```
Traceback (most recent call last):
  File "sage/misc/cachefunc.pyx", line 1007, in sage.misc.cachefunc.CachedFunction.__call__
    return self.cache[k]
  File "sage/misc/weak_dict.pyx", line 715, in sage.misc.weak_dict.WeakValueDictionary.__getitem__
    raise KeyError(k)
KeyError: ((<class 'sage.rings.real_arb.RealBallField'>, 53), ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/bin/sage-ipython", line 10, in <module>
    banner()
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/misc/banner.py", line 115, in banner
    print(banner_text(full=True))
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/misc/banner.py", line 70, in banner_text
    import sage.all
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/all.py", line 84, in <module>
    from sage.rings.all      import *
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/rings/all.py", line 55, in <module>
    from sage.rings.number_field.all import *
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/rings/number_field/all.py", line 2, in <module>
    from .number_field import (NumberField, NumberFieldTower, CyclotomicField, QuadraticField,
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/rings/number_field/number_field.py", line 216, in <module>
    from . import number_field_element_quadratic
  File "sage/rings/number_field/number_field_element_quadratic.pyx", line 1, in init sage.rings.number_field.number_field_element_quadratic
    # distutils: libraries = NTL_LIBRARIES
  File "sage/rings/real_arb.pyx", line 4064, in init sage.rings.real_arb
    RBF = RealBallField()
  File "sage/misc/classcall_metaclass.pyx", line 320, in sage.misc.classcall_metaclass.ClasscallMetaclass.__call__
    return cls.classcall(cls, *args, **kwds)
  File "sage/rings/real_arb.pyx", line 388, in sage.rings.real_arb.RealBallField.__classcall__
    return super().__classcall__(cls, precision)
  File "sage/misc/cachefunc.pyx", line 1012, in sage.misc.cachefunc.CachedFunction.__call__
    w = self.f(*args, **kwds)
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/structure/unique_representation.py", line 1010, in __classcall__
    instance = typecall(cls, *args, **options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sage/misc/classcall_metaclass.pyx", line 471, in sage.misc.classcall_metaclass.typecall
    return (<PyTypeObject*>type).tp_call(cls, args, kwds)
  File "sage/rings/real_arb.pyx", line 427, in sage.rings.real_arb.RealBallField.__init__
    self._populate_coercion_lists_(coerce_list=[ZZ, QQ], convert_method_name='_arb_')
  File "sage/structure/parent.pyx", line 1509, in sage.structure.parent.Parent._populate_coercion_lists_
    self.register_coercion(mor)
  File "sage/structure/parent.pyx", line 1655, in sage.structure.parent.Parent.register_coercion
    mor = self._generic_coerce_map(mor)
  File "sage/structure/parent.pyx", line 1932, in sage.structure.parent.Parent._generic_coerce_map
    return self._generic_convert_map(S, category=category)
  File "sage/structure/parent_old.pyx", line 301, in sage.structure.parent_old.Parent._generic_convert_map
    return parent.Parent._generic_convert_map(self, S, category)
  File "sage/structure/parent.pyx", line 1977, in sage.structure.parent.Parent._generic_convert_map
    return DefaultConvertMap_unique(S, self, category=category)
  File "sage/structure/coerce_maps.pyx", line 76, in sage.structure.coerce_maps.DefaultConvertMap.__init__
    parent = domain.Hom(codomain, category=category)
  File "sage/structure/parent.pyx", line 1341, in sage.structure.parent.Parent.Hom
    return Hom(self, codomain, category)
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/src/sage/categories/homset.py", line 440, in Hom
    raise ValueError("{} is not in {}".format(O, category))
ValueError: Integer Ring is not in Join of Category of euclidean domains and Category of infinite sets and Category of objects
```

**Comment by mkoeppe** [comment]
```
[sagelib-10.4.beta9] [spkg-install]     In file included from sage/matrix/change_ring.c:1267:
[sagelib-10.4.beta9] [spkg-install]     In file included from sage/libs/flint/flint_wrap.h:97:
[sagelib-10.4.beta9] [spkg-install]     /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/include/flint/fmpz_mpoly_factor.h:289:46: error: expected ')'
[sagelib-10.4.beta9] [spkg-install]     void fmpz_poly_pfrac_clear(fmpz_poly_pfrac_t I);
[sagelib-10.4.beta9] [spkg-install]                                                  ^
[sagelib-10.4.beta9] [spkg-install]     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
[sagelib-10.4.beta9] [spkg-install]     #define I _Complex_I
[sagelib-10.4.beta9] [spkg-install]               ^
[sagelib-10.4.beta9] [spkg-install]     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/complex.h:40:21: note: expanded from macro '_Complex_I'
[sagelib-10.4.beta9] [spkg-install]     #define _Complex_I (__extension__ 1.0iF)
[sagelib-10.4.beta9] [spkg-install]                         ^
[sagelib-10.4.beta9] [spkg-install]     /Users/mkoeppe/s/sage/sage-rebasing/worktree-pristine/local/include/flint/fmpz_mpoly_factor.h:289:46: note: to match this '('
[sagelib-10.4.beta9] [spkg-install]     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
[sagelib-10.4.beta9] [spkg-install]     #define I _Complex_I
[sagelib-10.4.beta9] [spkg-install]               ^
[sagelib-10.4.beta9] [spkg-install]     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/complex.h:40:20: note: expanded from macro '_Complex_I'
[sagelib-10.4.beta9] [spkg-install]     #define _Complex_I (__extension__ 1.0iF)
[sagelib-10.4.beta9] [spkg-install]                        ^
```

**Comment by mkoeppe** [comment]
Incompatible change in the `doctest` module from https://github.com/python/cpython/pull/108795/files leads to 
```
Traceback (most recent call last):
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/src/sage/doctest/forker.py", line 2589, in __call__
    doctests, extras = self._run(runner, options, results)
                       ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/src/sage/doctest/forker.py", line 2637, in _run
    result = runner.run(test)
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/src/sage/doctest/forker.py", line 913, in run
    return self._run(test, compileflags, out)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-clean/src/sage/doctest/forker.py", line 841, in _run
    self._DocTestRunner__record_outcome(test, failures, tries)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DocTestRunner.__record_outcome() missing 1 required positional argument: 'skips'

```

**Comment by kiwifb** [comment]
Good job I looked here. Well, I have spotted issues with sphinx 8 a few weeks back. `sage_autodoc.py` will need synchronising again and I am not sure that saying we can use something as low as sphinx-5.2 is fair.

In any case I am looking at doing the sage_autodoc.py work right now.

**Comment by kiwifb** [comment]
I have an updated sage_autodoc.py that works with sphinx 8.0.2, should I open a PR on your PR or put it in a separate PR you will depend on?

**Comment by kiwifb** [comment]
> Does the updated file work with older Sphinx too? Then a separate PR

I honestly do not know. I could test with 7.4.7 but I will not test further back.

**Comment by mkoeppe** [comment]
We'll only need to make sure it works with the version currently shipped with Sage, 7.3.7.
It's fine to update build/pkgs/sphinx/version_requirements.txt

**Comment by mkoeppe** [comment]
Alternatively, if supporting 7.4.x is easy but 7.3.x is not, we can also do an intermediate update of Sphinx to 7.4.7

**Comment by kiwifb** [comment]
I actually can go back to 7.3.7 without too much difficulties. I will try it later today.

**Comment by kiwifb** [comment]
So, sphinx 7.3.7 just broke down very quickly. But 7.4.7 does work. So, I guess I'll go with a PR with an update to 7.4.7 as a stepping stone.

**Comment by kiwifb** [comment]
I have opened #38549 for the update to sphinx 7.4.7 and the sage_autodoc.py update.
