### PR TITLE
Remove nitpick_patch_config function

### LINKED ISSUE #37996: sage doc does not even start to build with sphinx 7.3.7
### Steps To Reproduce

Found this while trying to build sage-doc in sage-on-gentoo with python 3.12 and sphinx 7.3.7/docutils-0.21.2 (downgrading docutils to a previous working version did not help)

### Expected Behavior

It builds successfully

### Actual Behavior

```
make -j8 doc-html 
mkdir -p en/reference/repl
sage -advanced > en/reference/repl/options.txt
make doc-inventory--reference-references
make[1]: Entering directory '/home/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc'
sage --docbuild --no-pdf-links reference/references inventory 
[reference] building [inventory]: targets for 1 source files that are out of date
[reference] updating environment: [new config] 1 added, 0 changed, 0 removed
[reference] Exception occurred:
[reference]   File "/usr/lib/python3.12/site-packages/sphinx/config.py", line 466, in __getstate__
[reference]     self._options[name] = opt = _Opt(*opt)
[reference]                                 ^^^^^^^^^^
[reference] TypeError: _Opt.__init__() missing 1 required positional argument: 'valid_types'
[reference] The full traceback has been saved in /home/portage/sci-mathematics/sage-doc-9999/temp/sphinx-err-lf9_1h84.log, if you want to report the issue to the developers.
[reference] Please also report this if it was a user error, so that a better error message can be provided next time.
[reference] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/sage_docbuild/__main__.py", line 514, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/sage_docbuild/__main__.py", line 510, in main
    builder()
  File "/usr/lib/python3.12/site-packages/sage_docbuild/builders.py", line 823, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/usr/lib/python3.12/site-packages/sage_docbuild/builders.py", line 163, in f
    runsphinx()
  File "/usr/lib/python3.12/site-packages/sage_docbuild/sphinxbuild.py", line 319, in runsphinx
    sys.stderr.raise_errors()
  File "/usr/lib/python3.12/site-packages/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
    raise OSError(self._error)
OSError: Exception occurred:

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean doc-uninstall" first and try again.
make[1]: *** [Makefile:28: doc-inventory--reference-references] Error 1
make[1]: Leaving directory '/home/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc'
make: *** [Makefile:40: doc-inventory-reference] Error 2
```

### Additional Information

_No response_

### Environment

```markdown
- gentoo
- sage 10.4.beta5
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

### PR DESCRIPTION
**Pull request by kwankyu**
Fixes #37996.

We remove this function 

```python
def nitpick_patch_config(app):
    """
    Patch the default config for nitpicky
    [...] ensure that nitpicky is not considered as a Sphinx
    environment variable but rather as a Sage environment variable. As a
    consequence, changing it doesn't force the recompilation of the entire
    documentation.
    """
    app.config.values['nitpicky'] = (False, 'sage')
    app.config.values['nitpick_ignore'] = ([], 'sage')
```
from `src/sage_docbuild/conf.py`.  

The original purpose of the function seems to change `"env"` to `"sage"` for `nitpicky` config variable. But the recent Sphinx is setting `""` (empty string) instead of `"env"` by default. See https://github.com/sphinx-doc/sphinx/blob/48cbb43e28efe82b198137042811e0ade3599ae7/sphinx/config.py#L250C1-L250C41

- Hence  the function is already no-op. But this old and obsolete function is the cause of #37996. Hence we simply remove it.

- To prepare for Sphinx 7.3.7, we also remove some code which seems to have become obsolete when `sage -clone` was removed long time ago.

- Made some docstring up-to-date, to test incremental doc build.

### :memo: Checklist

- [x] The title is concise and informative.
- [x] The description explains in detail what this PR is about.
- [x] I have linked a relevant issue or discussion.
- [ ] I have created tests covering the changes.
- [ ] I have updated the documentation and checked the documentation preview.

### CODE REVIEW

**Comment by collares** [comment]
I've tested a non-incremental build with Sphinx 7.3.7 and it looks good. Thanks!

**Comment by kwankyu** [comment]
Thanks. Then let us ship this PR.
