### ISSUE TITLE
Support GCC 13 (`fedora-38`)

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/sage#35092]
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Problem Description

`fedora-38` already ships GCC 13, which we reject.

### Proposed Solution

Updated spkg-configure and hope that nothing needs changes.

### Alternatives Considered

N/A

**Comment by mkoeppe** [comment]
After allowing GCC 13, `tox -e docker-fedora-38-minimal` reveals:
Building zeromq fails:
```
  [zeromq-4.3.4]   In file included from /usr/include/c++/13/ext/alloc_traits.h:34,
  [zeromq-4.3.4]                    from /usr/include/c++/13/bits/stl_uninitialized.h:64,
  [zeromq-4.3.4]                    from /usr/include/c++/13/vector:65,
  [zeromq-4.3.4]                    from src/epoll.hpp:37,
  [zeromq-4.3.4]                    from src/poller.hpp:46,
  [zeromq-4.3.4]                    from src/io_object.hpp:36,
  [zeromq-4.3.4]                    from src/ws_engine.hpp:33,
  [zeromq-4.3.4]                    from src/ws_engine.cpp:59:
  [zeromq-4.3.4]   /usr/include/c++/13/bits/alloc_traits.h: In instantiation of 'struct std::__allocator_traits_base::__rebind<zmq::secure_allocator_t<unsigned char>, unsigned char, void>':
  [zeromq-4.3.4]   /usr/include/c++/13/bits/alloc_traits.h:94:11:   required by substitution of 'template<class _Alloc, class _Up> using std::__alloc_rebind = typename std::__allocator_traits_base::__rebind<_Alloc, _Up>::type [with _Alloc = zmq::secure_allocator_t<unsigned char>; _Up = unsigned char]'
  [zeromq-4.3.4]   /usr/include/c++/13/bits/alloc_traits.h:228:8:   required by substitution of 'template<class _Alloc> template<class _Tp> using std::allocator_traits< <template-parameter-1-1> >::rebind_alloc = std::__alloc_rebind<_Alloc, _Tp> [with _Tp = unsigned char; _Alloc = zmq::secure_allocator_t<unsigned char>]'
  [zeromq-4.3.4]   /usr/include/c++/13/ext/alloc_traits.h:126:65:   required from 'struct __gnu_cxx::__alloc_traits<zmq::secure_allocator_t<unsigned char>, unsigned char>::rebind<unsigned char>'
  [zeromq-4.3.4]   /usr/include/c++/13/bits/stl_vector.h:88:21:   required from 'struct std::_Vector_base<unsigned char, zmq::secure_allocator_t<unsigned char> >'
  [zeromq-4.3.4]   /usr/include/c++/13/bits/stl_vector.h:423:11:   required from 'class std::vector<unsigned char, zmq::secure_allocator_t<unsigned char> >'
  [zeromq-4.3.4]   src/curve_client_tools.hpp:64:76:   required from here
  [zeromq-4.3.4]   /usr/include/c++/13/bits/alloc_traits.h:70:31: error: static assertion failed: allocator_traits<A>::rebind_alloc<A::value_type> must be A
  [zeromq-4.3.4]      70 |                         _Tp>::value,
  [zeromq-4.3.4]         |                               ^~~~~
  [zeromq-4.3.4]   /usr/include/c++/13/bits/alloc_traits.h:70:31: note: 'std::integral_constant<bool, false>::value' evaluates to false
  [zeromq-4.3.4]   make[4]: *** [Makefile:6176: src/libzmq_la-ws_engine.lo] Error 1
 ```

**Comment by mkoeppe** [comment]
Also 
```
[givaro-4.1.1] installing. Log file: /sage/logs/pkgs/givaro-4.1.1.log
  [givaro-4.1.1] error installing, exit status 1. End of log file:
  [givaro-4.1.1]      47 |         Degree& operator/=( const uint64_t& e) { _deg/=e; return *this; }
  [givaro-4.1.1]         |                                   ^~~~~~~~
  [givaro-4.1.1]   ./givaro/givdegree.h:47:35: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  [givaro-4.1.1]   make[7]: *** [Makefile:467: givdegree.lo] Error 1
  [givaro-4.1.1]   make[7]: Target 'all' not remade because of errors.
```

**Comment by mkoeppe** [comment]
Also
```
make[4]: *** No rule to make target '../libopenblas_haswellp-r0.3.21.a', needed by '../libopenblas_haswellp-r0.3.21.so'.
```
but that looks more like a makefile concurrency bug

**Comment by enriqueartal** [comment]
Is this relevant concerning zeromq? 
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=a47fe1a0456d92e34a2773b4f4393fa95254d860
And this for givaro?
https://packages.fedoraproject.org/pkgs/givaro/givaro/fedora-rawhide.html

**Comment by mkoeppe** [comment]
Thanks for finding these! This looks like what we need.
The givaro link led me to https://src.fedoraproject.org/rpms/givaro/c/9af877e0232db5ca416e77ccd18068497241a5db?branch=rawhide

**Comment by mkoeppe** [comment]
Also `libgd` fails to build (it is not accepted from the system).
```
https://mirror.csclub.uwaterloo.ca/sage/spkg/upstream/libgd/libgd-2.3.2.tar.xz
[......................................................................]
libgd-2.3.2
====================================================
Setting up build directory for libgd-2.3.2
Finished extraction
No patch files found in ../patches
****************************************************
Host system:
Linux 7f0f1cb4e690 5.15.0-1035-azure #42-Ubuntu SMP Tue Feb 28 19:41:23 UTC 2023 x86_64 GNU/Linux
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/sage/local/libexec/gcc/x86_64-pc-linux-gnu/12.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../src/configure --prefix=/sage/local --with-local-prefix=/sage/local --with-system-zlib --without-isl --disable-multilib --disable-nls --disable-libitm --enable-languages=c,c++,fortran   CXX=g++
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.0 (GCC) 
****************************************************
Package 'libgd' is currently not installed
Uninstalling 'libgd' with legacy uninstaller
rm: cannot remove '/sage/local/lib/libgd.*': No such file or directory
Error during uninstallation of 'libgd': Command '['/sage/build/pkgs/libgd/spkg-legacy-uninstall']' returned non-zero exit status 1.
Configuring libgd-2.3.2
configure: WARNING: unrecognized options: --disable-maintainer-mode
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking the archiver (ar) interface... ar
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3145728
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether ln -s works... yes
checking whether to support xpm... no
checking whether to support tiff... auto
checking for libtiff-4... yes
checking whether to support webp... auto
checking for libwebp... yes
checking whether to support heif... auto
checking for libheif >= 1.7.0... no
checking for heif_get_version in -lheif... no
configure: Disabling support for heif
checking whether to support avif... no
checking for simple visibility declarations... yes
checking whether we are building for a Win32 host... no
checking CFLAGS for maximum warnings... -Wall

** Configuration summary for libgd 2.3.2:

   Support for gd/gd2 images:        yes
   Support for Zlib:                 yes
   Support for PNG library:          yes
   Support for JPEG library:         no
   Support for WebP library:         yes
   Support for HEIF library:         no
   Support for AVIF library:         no
   Support for TIFF library:         yes
   Support for Freetype 2.x library: yes
   Support for Fontconfig library:   no
   Support for Xpm library:          no
   Support for liq library:          no
   Support for complex text:         no
   Support for pthreads:             yes

[...]
Building libgd-2.3.2
Making all in src
make  all-am
gcc -DHAVE_CONFIG_H -I.   -I/sage/local/include   -I/usr/include/libpng16  -I/sage/local/include -I/sage/local/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread     -I/usr/include/webp   -g -g -O2 -fvisibility=hidden -Wall -c -o gdcmpgif.o gdcmpgif.c
[...]
  [libgd-2.3.2]   /usr/bin/bash ../libtool  --tag=CC   --mode=link gcc  -g -g -O2 -fvisibility=hidden -Wall  -Wl,-rpath-link,/sage/local/lib -L/sage/local/lib -Wl,-rpath,/sage/local/lib -Wl,-rpath-link,/sage/local/lib -L/sage/local/lib -Wl,-rpath,/sage/local/lib  -o giftogd2 giftogd2.o libgd.la  -lm  -L/sage/local/lib -lz   -lpng16 -lz  -L/sage/local/lib -lfreetype   -ltiff   -lwebp -lsharpyuv 
  [libgd-2.3.2]   libtool: link: gcc -g -g -O2 -fvisibility=hidden -Wall -Wl,-rpath-link -Wl,/sage/local/lib -Wl,-rpath -Wl,/sage/local/lib -Wl,-rpath-link -Wl,/sage/local/lib -Wl,-rpath -Wl,/sage/local/lib -o .libs/giftogd2 giftogd2.o  -L/sage/local/lib ./.libs/libgd.so -lm -lpng16 -lz -lfreetype -ltiff -lwebp -lsharpyuv -Wl,-rpath -Wl,/sage/local/lib
  [libgd-2.3.2]   /usr/bin/ld: /usr/lib64/libharfbuzz.so.0: undefined reference to `FT_Get_Transform'
  [libgd-2.3.2]   /usr/bin/ld: /usr/lib64/libharfbuzz.so.0: undefined reference to `FT_Get_Color_Glyph_Paint'
  [libgd-2.3.2]   /usr/bin/ld: /usr/lib64/libharfbuzz.so.0: undefined reference to `FT_Get_Color_Glyph_ClipBox'
  [libgd-2.3.2]   /usr/bin/ld: /usr/lib64/libharfbuzz.so.0: undefined reference to `FT_Get_Paint_Layers'
  [libgd-2.3.2]   /usr/bin/ld: /usr/lib64/libharfbuzz.so.0: undefined reference to `FT_Get_Colorline_Stops'
  [libgd-2.3.2]   /usr/bin/ld: /usr/lib64/libharfbuzz.so.0: undefined reference to `FT_Get_Paint'
  [libgd-2.3.2]   collect2: error: ld returned 1 exit status
  [libgd-2.3.2]   make[5]: *** [Makefile:859: giftogd2] Error 1
  [libgd-2.3.2]   make[5]: Target 'all-am' not remade because of errors.
  [libgd-2.3.2]   make[4]: *** [Makefile:644: all] Error 2
  [libgd-2.3.2]   Making all in config
  [libgd-2.3.2]   make[4]: Nothing to be done for 'all'.
  [libgd-2.3.2]   Making all in tests
  [libgd-2.3.2]   make[4]: Nothing to be done for 'all'.
  [libgd-2.3.2]   make[4]: Nothing to be done for 'all-am'.
  [libgd-2.3.2]   make[3]: *** [Makefile:426: all-recursive] Error 1
  [libgd-2.3.2]   make[3]: Target 'all' not remade because of errors.
  [libgd-2.3.2]   ********************************************************************************
  [libgd-2.3.2]   Error building libgd-2.3.2
  [libgd-2.3.2]   ********************************************************************************
```

**Comment by enriqueartal** [comment]
Fedora 38 uses libgd-2.3.3 (actually also Fedora 37)

**Comment by mkoeppe** [comment]
I'm already preparing an upgrade PR

**Comment by enriqueartal** [comment]
After upgrading to Fedora 38, an incremental building of the develop branch (actually one of my branches merged with develop) failed; though openblas was in the system it tried to compile with a failure `libopenblas_atomp-r0.3.21.a] Bus error (core dumped)`. Actually it compiled gfortran 12; I changed to admit gfortran 13 with the same failure. After `make distclean` everything is fine, it took gfortran and openblas from the system

**Comment by mkoeppe** [comment]
On fedora-38-minimal, openblas 0.3.23 still fails to build
```
 [openblas-0.3.23]   ar: ../libopenblasp-r0.3.23.a(dsyevd.o):2: unexpected character `\016' in S-record file
  [openblas-0.3.23]   bfd plugin: ../libopenblasp-r0.3.23.a: file too short
  [openblas-0.3.23]   ar: ../libopenblasp-r0.3.23.a(dsyevd.o):2: unexpected character `\016' in S-record file
  [openblas-0.3.23]   make[4]: warning: -j2 forced in submake: resetting jobserver mode.
  [openblas-0.3.23]   ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 0 1 1 1 1 > linktest.c
  [openblas-0.3.23]   gcc -g -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=2 -DMAX_PARALLEL_NUMBER=1 -DUSE_TLS -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.23\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=2 -DMAX_PARALLEL_NUMBER=1 -DUSE_TLS -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.23\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I.. -Wl,-rpath-link,/sage/local/lib -L/sage/local/lib -Wl,-rpath,/sage/local/lib -Wl,-rpath-link,/sage/local/lib -L/sage/local/lib -Wl,-rpath,/sage/local/lib  -shared -o ../libopenblasp-r0.3.23.so \
  [openblas-0.3.23]   -Wl,--whole-archive ../libopenblasp-r0.3.23.a -Wl,--no-whole-archive \
  [openblas-0.3.23]   -Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
  [openblas-0.3.23]   /usr/bin/ld: ../libopenblasp-r0.3.23.a: member ../libopenblasp-r0.3.23.a(saxpy.o) in archive is not an object
  [openblas-0.3.23]   collect2: error: ld returned 1 exit status
  [openblas-0.3.23]   make[4]: *** [Makefile:195: ../libopenblasp-r0.3.23.so] Error 1
  [openblas-0.3.23]   make[4]: Target 'so' not remade because of errors.
  [openblas-0.3.23]   make[3]: *** [Makefile:132: shared] Error 2
```
https://github.com/sagemath/sage/actions/runs/6207962004/job/16858997112

**Comment by enriqueartal** [comment]
In Fedora 38, system openblas seems to work

**Comment by mkoeppe** [comment]
Yes, we know that it does. Above failure is for building the SPKG.

**Comment by mkoeppe** [comment]
I tried building 0.3.24, same result.
But it succeeded when I used `MAKE="make -j1"`.
So there seems to a parallelization bug in the makefile

**Comment by mkoeppe** [comment]
With #36663 and #36712 merged, we can close it as completed.
